// Amalgamated vUPF single-file source
// This file is auto-generated by concatenating all core .cpp and .hpp files.
// Place in: C:\Users\Alexey\Desktop\min\vNE\vUPF\UPF\upf_amalgamated.cpp

// ================= HEADER SECTION =================
// -- upf/interfaces.hpp --
#pragma once
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <unordered_map>
#include <memory>

namespace upf {
// ... (interfaces.hpp content here, see above)
}

// -- upf/cli.hpp --
#pragma once
#include "upf/node.hpp"
#include "upf/config/runtime_config.hpp"
#include <string>
#include <memory>
namespace upf {
// ... (cli.hpp content here, see above)
}

// -- upf/adapters/console_adapters.hpp --
#pragma once
#include "upf/modules/n6_packet_buffer.hpp"
#include <cstddef>
#include <iostream>
#include <mutex>
#include <unordered_set>
#include <string>
#include <unordered_map>
#include <vector>
#include "upf/interfaces.hpp"
namespace upf {
// ... (console_adapters.hpp content here, see above)
}

// -- upf/adapters/network_adapters.hpp --
#pragma once
#include "upf/interfaces.hpp"
#include "upf/modules/n6_packet_buffer.hpp"
#include <atomic>
#include <cstddef>
#include <memory>
#include <mutex>
#include <queue>
#include <thread>
#include <unordered_map>
#include <unordered_set>
namespace upf {
// ... (network_adapters.hpp content here, see above)
}

// -- upf/config/runtime_config.hpp --
#pragma once
#include <string>
#include <cstdint>
namespace upf {
// ... (runtime_config.hpp content here, see above)
}

// -- upf/modules/observability.hpp --
#pragma once
#include "upf/config/runtime_config.hpp"
#include <string>
#include <chrono>
namespace upf {
// ... (observability.hpp content here, see above)
}

// -- upf/modules/session_table.hpp --
#pragma once
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>
#include "upf/interfaces.hpp"
namespace upf {
// ... (session_table.hpp content here, see above)
}

// -- upf/modules/transport_serialization.hpp --
#pragma once
#include <string>
#include "upf/interfaces.hpp"
namespace upf {
// ... (transport_serialization.hpp content here, see above)
}

// -- upf/modules/n6_packet_buffer.hpp --
#pragma once
#include "upf/interfaces.hpp"
#include <cstddef>
#include <deque>
#include <mutex>
#include <optional>
#include <string>
#include <unordered_map>
namespace upf {
// ... (n6_packet_buffer.hpp content here, see above)
}

// -- upf/protocol/pfcp_wire.hpp --
#pragma once
#include "upf/interfaces.hpp"
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
namespace upf::pfcp {
// ... (pfcp_wire.hpp content here, see above)
}

// ================= IMPLEMENTATION SECTION =================
// -- src/main.cpp --
#include <iostream>
#include <iomanip>
#include <chrono>
#include <sstream>
#include <cstdlib>
#include <string>
#include <optional>
#include <filesystem>
// ... (main.cpp content here, see above)

// -- src/cli.cpp --
// ... (cli.cpp content here, see above)

// -- src/upf.cpp --
// ... (upf.cpp content here, see above)

// -- src/adapters/console_adapters.cpp --
// ... (console_adapters.cpp content here, see above)

// -- src/adapters/network_adapters.cpp --
// ... (network_adapters.cpp content here, see above)

// -- src/config/runtime_config.cpp --
// ... (runtime_config.cpp content here, see above)

// -- src/modules/observability.cpp --
// ... (observability.cpp content here, see above)

// -- src/modules/session_table.cpp --
// ... (session_table.cpp content here, see above)

// -- src/modules/transport_serialization.cpp --
// ... (transport_serialization.cpp content here, see above)

// -- src/modules/n6_packet_buffer.cpp --
// ... (n6_packet_buffer.cpp content here, see above)

// -- src/protocol/pfcp_wire.cpp --
// ... (pfcp_wire.cpp content here, see above)

// -- src/node.cpp --
// ... (node.cpp content here, see above)

// -- src/n6_traffic_tool.cpp --
// ... (n6_traffic_tool.cpp content here, see above)

// End of amalgamated file
